package com.karnadigital.omnisuite.feature.home

sealed class NavigationEvent {
    data object NavigateToSettings : NavigationEvent()
    data object NavigateToQrGenerator : NavigationEvent()
    data object NavigateToBarcodeScanner : NavigationEvent()
    data object NavigateToImageTools : NavigationEvent()
    data class NavigateToImageToolsWithTab(val tab: Int = 0) : NavigationEvent()
    data object NavigateToPdfMerge : NavigationEvent()
    data object NavigateToPdfSplit : NavigationEvent()
    data object NavigateToPdfLock : NavigationEvent()
    data object NavigateToDocToPdf : NavigationEvent()
    data object NavigateToPptToPdf : NavigationEvent()
    data object NavigateToScanToPdf : NavigationEvent()
    data object NavigateToPdfToImages : NavigationEvent()
    data object NavigateToOcr : NavigationEvent()
    data object NavigateToSignaturePad : NavigationEvent()
    data object NavigateToWatermark : NavigationEvent()
    data object NavigateToPdfToWord : NavigationEvent()
    data object NavigateToPdfToPpt : NavigationEvent()
    data object NavigateToPdfToExcel : NavigationEvent()
    data object NavigateToPdfFormFiller : NavigationEvent()
    data object NavigateToImagesToPdf : NavigationEvent()
    data object NavigateToPdfCompress : NavigationEvent()
    data object NavigateToPdfFlatten : NavigationEvent()
    data object NavigateToXlsToPdf : NavigationEvent()
    data object NavigateToBatchTools : NavigationEvent()
    data object NavigateToZipMaker : NavigationEvent()
    data object NavigateToPdfDecrypt : NavigationEvent()
    data object NavigateToPdfRotate : NavigationEvent()
    data object NavigateToPdfExtract : NavigationEvent()
    data object NavigateToPdfDelete : NavigationEvent()
    data object NavigateToWebToPdf : NavigationEvent()
    data object NavigateToHtmlToPdf : NavigationEvent()
    data object NavigateToMarkdownToPdf : NavigationEvent()
    data object NavigateToDocxToTxt : NavigationEvent()
    data object NavigateToCsvToXlsx : NavigationEvent()
    data object NavigateToXlsxToCsv : NavigationEvent()
    data object NavigateToPptxToTxt : NavigationEvent()
    data object NavigateToTarTools : NavigationEvent()
    data object NavigateToHistory : NavigationEvent()
    data object NavigateToPdfPageNumber : NavigationEvent()
    data object NavigateToPdfReorder : NavigationEvent()
    data object NavigateToPdfExtractImages : NavigationEvent()
    data object NavigateToTxtToPdf : NavigationEvent()
    data object NavigateToCsvToPdf : NavigationEvent()
    data object NavigateToPdfToTxt : NavigationEvent()
    data object NavigateToImagesToPdfLayout : NavigationEvent()
    data object NavigateToPdfHeaderFooter : NavigationEvent()
    data object NavigateToPdfResize : NavigationEvent()
    data object NavigateToPasswordZip : NavigationEvent()
    data object NavigateToPdfToPdfA : NavigationEvent()
    data object NavigateToPdfMetadata : NavigationEvent()
    data object NavigateToPdfCropMargins : NavigationEvent()
    data object NavigateToPdfRedact : NavigationEvent()
    data object NavigateToPdfRepair : NavigationEvent()
    data object NavigateToPdfOverlay : NavigationEvent()
    data object NavigateToPdfCompare : NavigationEvent()
    data object NavigateToPdfToMarkdown : NavigationEvent()
    data object NavigateToPdfSplitBySize : NavigationEvent()
    data object NavigateToPdfInsertPages : NavigationEvent()
    data object NavigateToPdfReplacePages : NavigationEvent()
    data object NavigateToPdfBookmarks : NavigationEvent()
    data object NavigateToPasswordZipExtract : NavigationEvent()
    data object NavigateToPdfSplitByBookmarks : NavigationEvent()
    data object NavigateToPdfUnderlay : NavigationEvent()
    data object NavigateToPdfFormCreation : NavigationEvent()
    data object NavigateToFileEncrypt : NavigationEvent()
    data object NavigateToFileDecrypt : NavigationEvent()
    data object NavigateToPdfSelectiveImageExtract : NavigationEvent()
    data object NavigateToPdfAllPagesToImage : NavigationEvent()
    data object NavigateToFileChecksum : NavigationEvent()
    data object NavigateToTextCompare : NavigationEvent()
    data class OpenFile(val fileUri: String) : NavigationEvent()
    data class OpenSequentialImages(val imageUris: List<String>, val title: String = "Extracted Images") : NavigationEvent()
    data class SelectFileForType(val type: String) : NavigationEvent()
}
